### PR TITLE
Fix #285: Short declaration doesn't compile with opcode return value.

### LINKED ISSUE #285: Short declaration doesn't compile with opcode return value
**To Reproduce**
```
package main
func main()() {
	f := i32.f32(0)
}
```
**Expected behavior**
Should compile
**Screenshots**
```
error: tests/pending_6.cx:4 function 'i32.f32' expected receiving variable of type 'f32'; 'i32' was provided
```

**Desktop:**
 - OS: Linux
 - CX Version : 0.6.1, https://github.com/skycoin/cx/commit/d8775bfb4500fde31a074507713fc0de47b64e11

### PR DESCRIPTION
**Pull request by amherag**
Fixes #285 

Changes:
- Most of the times, outputs in short declarations can adopt the operator's input type. This is not the case for parse functions (and we'd need to check if it's the case for other functions).

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/actions/assignment.go [hunk 1]
```diff
@@ -238,7 +238,7 @@ func Assignment(to []*CXExpression, assignOp string, from []*CXExpression) []*CX
 		} else {
 			// we'll delegate multiple-value returns to the 'expression' grammar rule
 			// only assigning as if the operator had only one output defined
-
+
```
Comment (ingwal) [inline cxgo/actions/assignment.go]: Is this really ok with the format script?
