### PR TITLE
Fix #99: Short variable declarations are not working with calls to me…

### LINKED ISSUE #99: Short variable declarations are not working with calls to methods or functions
Most likely the variable is trying to adopt the method's identifier's type, instead of the method's output's type.

```
package graphical2d

type ProgressBar struct {
  value     f32
  max_value f32
}

func newProgressBar(max_value f32) (progress_bar ProgressBar) {
  progress_bar = ProgressBar{
    value: 1.0,
    max_value: max_value}
}

func (progress_bar ProgressBar) getValue() (value f32) {
  value = progress_bar.value;
  return value;
}


package main

import "graphical2d"

func main() {
  var pb ProgressBar
  pb = graphical2d.newProgressBar(100.0);

  a := pb.getValue()
  f32.print(a)
}
```

### PR DESCRIPTION
**Pull request by amherag**
…thods or functions

Fixes #99

Changes:
- Short declarations now work with calls to methods

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/actions/functions.go [hunk 1]
```diff
@@ -127,8 +127,13 @@ func FunctionDeclaration(fn *CXFunction, inputs, outputs []*CXArgument, exprs []
...
 		if len(expr.Outputs) > 0 && len(expr.Inputs) > 0 && expr.Outputs[0].IsShortDeclaration && !expr.IsStructLiteral {
-			fn.Expressions[i-1].Outputs[0].Type = fn.Expressions[i].Inputs[0].Type
-			fn.Expressions[i].Outputs[0].Type = fn.Expressions[i].Inputs[0].Type
+			if expr.IsMethodCall {
+				fn.Expressions[i-1].Outputs[0].Type = fn.Expressions[i].Operator.Outputs[0].Type
+				fn.Expressions[i].Outputs[0].Type = fn.Expressions[i].Operator.Outputs[0].Type
+			} else {
+				fn.Expressions[i-1].Outputs[0].Type = fn.Expressions[i].Inputs[0].Type
+				fn.Expressions[i].Outputs[0].Type = fn.Expressions[i].Inputs[0].Type
+			}
```
Comment (ingwal) [inline cxgo/actions/functions.go]: I understand exactly 0 (zero, zilch, nil) of this change.  Please explain it so that I can add the explanation to my documentation of CXExpression.
