### PR TITLE
Fix #58: No compilation error when indexing an array with a non integ…

### LINKED ISSUE #58: No compilation error when indexing an array with a non integral var.
```
package main

type AA struct {
   f f32
}

func main()() {
    var ai [4]i32
    ai = [4]i32{11, 22, 33, 44}

    var a AA
    printf("ai[a] == %d, this should not compile\n", ai[a])

    var f f32 = 0.0
    printf("ai[f] == %d, this should not compile\n", ai[f])

    var s str = "hello"
    printf("ai[s] == %d, this should not compilee\n", ai[s])
    printf(`ai["hello"] == %d, this should not compilee\n`, ai["hello"])

    printf("ai[2.0] == %d, this should not compilee\n", ai[2.0]) // panic when indexing with float literal
}
```
output 1:
```
ai[a] == 11, this should not compile
ai[f] == 11, this should not compile
ai[s] == 22, this should not compilee
ai["hello"] == 22, this should not compilee
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cx.ReadMemory(...)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:131
github.com/skycoin/cx/cx.ReadI32(0x0, 0xc4200ed040, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:342 +0xbb
github.com/skycoin/cx/cx.buildString(0xc42008df40, 0x0, 0x1, 0x2c, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:499 +0x3fb
github.com/skycoin/cx/cx.op_printf(0xc42008df40, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:530 +0x39
github.com/skycoin/cx/cx.execNative(0xc420072f70)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes.go:417 +0x2c1
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc4201f4000, 0xc420072f70, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:252 +0x31f
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc420072f70, 0x0, 0x4, 0xc4201ca420)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:171 +0x2ba
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8598 +0x1d08
```
output 2 (when commenting the line "f f32"):
```
2018/09/20 22:22:07 Not enough buffer data to deserialize
panic: Not enough buffer data to deserialize

goroutine 1 [running, locked to thread]:
log.Panic(0xc420081338, 0x1, 0x1)
	/usr/local/go/src/log/log.go:326 +0xc0
github.com/skycoin/skycoin/src/cipher/encoder.DeserializeAtomic(0xc4201fa020, 0x0, 0x927a4, 0x80e200, 0xc4200813a0)
	/home/reash/go/src/github.com/skycoin/skycoin/src/cipher/encoder/encoder.go:136 +0x96
github.com/skycoin/cx/cx.ReadI32(0x0, 0xc420444a00, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:342 +0xac
github.com/skycoin/cx/cx.CalculateDereferences(0xc4204448c0, 0xc420081480, 0x0, 0xc420081400)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:27 +0x9f
github.com/skycoin/cx/cx.GetFinalOffset(0x0, 0xc4204448c0, 0x10)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:70 +0x66
github.com/skycoin/cx/cx.ReadI32(0x0, 0xc4204448c0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:341 +0x41
github.com/skycoin/cx/cx.buildString(0xc42008d360, 0x0, 0x10, 0x927b4, 0x7fa1c4eee6c8)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:499 +0x3fb
github.com/skycoin/cx/cx.op_printf(0xc42008d360, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:530 +0x39
github.com/skycoin/cx/cx.execNative(0xc420072f70)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes.go:417 +0x2c1
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc4201f0000, 0xc420072f70, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:252 +0x31f
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc420072f70, 0x0, 0x4, 0xc4201c6420)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:171 +0x2ba
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8598 +0x1d08
```

### PR DESCRIPTION
**Pull request by amherag**
…ral var.

Fixes #58

Changes:
- If you try to use a value of a type different than i32 or i64 to access an index of an array or slice, you'll now get an error.

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/actions/functions.go [hunk 1]
```diff
@@ -328,6 +328,14 @@ func processTestExpression (expr *CXExpression) {
 	}
 }
 
+// checkIndexType throws an error if the type of `idx` is not `i32` or `i64`.
+func checkIndexType (idx *CXArgument) {
```
Comment (ingwal) [inline cxgo/actions/functions.go]: This name is not good.  What would you think that the function "checkIndexType()" would do if you didn't know?  I suggest either isInteger() or isIndexType() or something similar.

File: cxgo/actions/functions.go [hunk 2]
```diff
@@ -360,6 +368,7 @@ func ProcessExpressionArguments(symbols *[]map[string]*CXArgument, symbolsScope
 		for _, idx := range arg.Indexes {
 			UpdateSymbolsTable(symbols, idx, offset, true)
 			GiveOffset(symbols, idx, offset, true)
+			checkIndexType(idx)
```
Comment (ingwal) [inline cxgo/actions/functions.go]: Hmm, the control flow here is not easy to follow.  Is this the only place where a check for index type will happen?  I would suggest something like 
if !isIndexType(...) {
    println(CompilationError(...))
}
That way the index checker is easier to reuse and the control flow is easier to follow.
