### PR TITLE
Fix #154: Sending pointers to slices to functions is now possible

### LINKED ISSUE #154: Cx stack overflow when appending to a slice passed by address
```
package main

func fooa(slice *[]i32) (out []i32){
	out = append(*slice, 1)
}

func foob(slice *[]i32) () {
	*slice = append(*slice, 1)
}

func main()() {
	var si []i32
	si = append(si, 1)
	si = fooa(&si)
	test(len(si), 2, "")

	var sk []i32
	sk = append(sk, 1)
	foob(&sk)
	test(len(sk), 2, "")
}
```
output:
```
byts1 [1 0 0 0]
byts2 [2 0 0 0]
pending_1.cx: 15: result was not equal to the expected value
error: pending_1.cx:8 stack exhausted

===Callstack===
>>> foob()
Inputs
	pending_1.cx:7 : foob() : []
>>> main()
Expressions
 	pending_1.cx:13 : append() : []
	pending_1.cx:15 : len() : 0
	pending_1.cx:18 : append() : []
	pending_1.cx:20 : len() : 0

goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc42009a008, 0x850700, 0xc42079c110)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/skycoin/cx/cx.runtimeErrorInfo(0x850700, 0x971e00, 0x971e01)
	/home/reash/go/src/github.com/skycoin/cx/cx/utilities.go:705 +0x115
github.com/skycoin/cx/cx.RuntimeError()
	/home/reash/go/src/github.com/skycoin/cx/cx/utilities.go:725 +0x12b
panic(0x850700, 0x971e00)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/skycoin/cx/cx.AllocateSeq(0x10b700011, 0x4)
	/home/reash/go/src/github.com/skycoin/cx/cx/op.go:190 +0xb8
github.com/skycoin/cx/cx.op_append(0xc4200a8b40, 0x10)
	/home/reash/go/src/github.com/skycoin/cx/cx/op_und.go:445 +0xa96
github.com/skycoin/cx/cx.init.1.func1(0xc4203bc000)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes_bare.go:847 +0x1297
github.com/skycoin/cx/cx.init.3.func1(0xc4203bc000)
	/home/reash/go/src/github.com/skycoin/cx/cx/opcodes_extra.go:316 +0xea6
github.com/skycoin/cx/cx.(*CXCall).ccall(0xc420246018, 0xc4203bc000, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:300 +0x33c
github.com/skycoin/cx/cx.(*CXProgram).Run(0xc4203bc000, 0x916401, 0xc420059a80, 0xffffffffffffffff, 0x0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:115 +0xdc
github.com/skycoin/cx/cx.(*CXProgram).RunCompiled(0xc4203bc000, 0x0, 0xc420059ab8, 0x0, 0x0, 0xc4200b60b0, 0x0)
	/home/reash/go/src/github.com/skycoin/cx/cx/execute.go:196 +0x260
main.main()
	/home/reash/go/src/github.com/skycoin/cx/cxgo/cxgo.nn.go:8624 +0x1bac
```

### PR DESCRIPTION
**Pull request by amherag**
Fixes #154 

Changes:
- Sending pointers to slices to functions is now possible

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/actions/functions.go [hunk 1]
```diff
@@ -563,7 +563,9 @@ func ProcessSliceAssignment(expr *CXExpression) {
 		for _, inp := range expr.Inputs {
 			assignElt := GetAssignmentElement(inp)
 
-			if assignElt.IsSlice && len(assignElt.Indexes) == 0 {
+			// we want to pass by value if we're sending the slice as a whole (no indexing)
+			// unless it's a pointer to the slice
+			if assignElt.IsSlice && len(assignElt.Indexes) == 0 && !hasDeclSpec(assignElt, DECL_POINTER) {
```
Comment (ingwal) [inline cxgo/actions/functions.go]: This looks as if you're checking that there is a pointer anywhere in the type in general (see the definition of hasDeclSpecI, not if it's a pointer to a slice in particular.  Is that true?
