### PR TITLE
Error in address used to generate a CSRF token. Port was 6001 instead…

### LINKED ISSUE #373: cx --broadcast panic: Get http://127.0.0.1:6001/api/v1/csrf
**Describe the bug**
cx --secret-key "c979d90a761cc063793a839978c9a1a1c8b721bd90822a3f3acc9f65e188e416" --broadcast examples/blockchain/counter-txn.cx
Blockchain counter: 1
panic: Get http://127.0.0.1:6001/api/v1/csrf: EOF

goroutine 1 [running, locked to thread]:
main.main()
	/home/yanito/go/src/github.com/skycoin/cx/cxgo/main.go:886 +0x50c6

**To Reproduce**
1. cd ~/go/src/github.com/skycoin/cx
2. git stash
3. skycoin-cli addressGen
4. update address and public key at fiber.toml
5.  cx --blockchain --secret-key "c979d90a761cc063793a839978c9a1a1c8b721bd90822a3f3acc9f65e188e416" ./examples/blockchain/counter-bc.cx
6. cx --publisher --genesis-address "p1tAgjsLmwJ3tLyaKCMBwtRW7KU18gDx27" --genesis-signature "a8ea6b98fff9d9b320728cf36fe764ce8644988f6cecc513d1ced359254a5d682f0a2a8ca1d1229bf26b32ffa327502bba341688f9c5bfb695ca9be140ee7a3f00" --secret-key "c979d90a761cc063793a839978c9a1a1c8b721bd90822a3f3acc9f65e188e416" --public-key "035cb75e77f9595f649125cdaa93817c7326607afa0e85b822b2c9b979120466f6"
7. open new terminal window with current cx path (terminal 2)
8. cx --peer --genesis-address "p1tAgjsLmwJ3tLyaKCMBwtRW7KU18gDx27" --port 6001 --genesis-signature "a8ea6b98fff9d9b320728cf36fe764ce8644988f6cecc513d1ced359254a5d682f0a2a8ca1d1229bf26b32ffa327502bba341688f9c5bfb695ca9be140ee7a3f00" --public-key "035cb75e77f9595f649125cdaa93817c7326607afa0e85b822b2c9b979120466f6"
9. open new terminal window with current cx path (terminal 3)
10. cx --create-wallet --wallet-seed "museum nothing practice weird wheel dignity economy attend mask recipe minor dress"
11. go back terminal 2, Ctrl+C
12. cx --peer --genesis-address "p1tAgjsLmwJ3tLyaKCMBwtRW7KU18gDx27" --port 6001 --genesis-signature "a8ea6b98fff9d9b320728cf36fe764ce8644988f6cecc513d1ced359254a5d682f0a2a8ca1d1229bf26b32ffa327502bba341688f9c5bfb695ca9be140ee7a3f00" --public-key "035cb75e77f9595f649125cdaa93817c7326607afa0e85b822b2c9b979120466f6"
13. go to terminal 3
14. cx --transaction examples/blockchain/counter-txn.cx
15. cx --secret-key "c979d90a761cc063793a839978c9a1a1c8b721bd90822a3f3acc9f65e188e416" --broadcast examples/blockchain/counter-txn.cx

### PR DESCRIPTION
**Pull request by amherag**
… of 6421

Fixes #373

Changes:
- Changed `options.port` to `options.port + 420` in the address used to get a CSRF token. 

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/main.go [hunk 1]
```diff
@@ -879,7 +879,7 @@ func main () {
 
 			// All these HTTP requests need to be dropped in favor of calls to calls to functions
 			// from the `cli` or `api` Skycoin packages
-			addr := fmt.Sprintf("http://127.0.0.1:%d", options.port)
+			addr := fmt.Sprintf("http://127.0.0.1:%d", options.port + 420)
```
Comment (ingwal) [inline cxgo/main.go]: The 420 is probably correct, but it is a very magic number.  Where does it come from?  Shouldn't it be a constant instead?
(Besides there is a "calls to calls to" in the comment above.)

File: cxgo/main.go [hunk 2]
```diff
@@ -894,6 +894,7 @@ func main () {
 			dataMap["hours_selection"] = map[string]string{"type": "manual"}
 			dataMap["wallet"] = map[string]string{"id": options.walletId}
 			dataMap["to"] = []interface{}{map[string]string{"address": "2PBcLADETphmqWV7sujRZdh3UcabssgKAEB", "coins": "1", "hours": "0"}}
+
```
Comment (ingwal) [inline cxgo/main.go]: why this empty line?
