### PR TITLE
Fix #309: Serialization is not taking into account non-default stack …

### LINKED ISSUE #309: Serialization is not taking into account non-default stack sizes.
**Describe the bug**
A CX program is not recording meta-data about its stack size. This is problematic for serialization because we can't know where the data segment starts. This error was not being detected because CX programs had a constant stack-size before (it was not configurable).

**To Reproduce**
1. Deserialize a CX program that was serialized with a stack size different than the stack size set in the CX installation that is deserializing the program.

**Expected behavior**
A CX program needs to record its stack size.

**Desktop (please complete the following information):**
 - CX Version [e.g. 0.6.2]

### PR DESCRIPTION
**Pull request by amherag**
…sizes.

Fixes #309

Changes:
- Just added a StackSize field to CXProgram and added it to the serialization and deserialization functions in cx/serialize.go

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cx/cxprogram.go [hunk 1]
```diff
@@ -23,32 +23,33 @@ import (
...
-	Inputs       []*CXArgument
-	Outputs      []*CXArgument
-	Memory       []byte // Used when running the program
-	HeapStartsAt int
-	StackPointer int
-	CallStack    []CXCall
-	CallCounter  int
-	HeapPointer  int
-	Terminated   bool
+	Inputs       []*CXArgument // OS input arguments
```
Comment (ingwal) [inline cx/cxprogram.go]: What is OS?

Comment (amherag) [reply cx/cxprogram.go]: Operating system.
