### PR TITLE
Fix #310: Splitting a serialized program into its blockchain and tran…

### LINKED ISSUE #310: Splitting a serialized program into its blockchain and transaction parts
**Describe the bug**
We need a way to split a serialized program in order to separate the blockchain code (the serialization with the program state) and the transaction code (the serialization containing the instructions to be run with the stored program state).

**To Reproduce**
1. Run a CX program in `--transaction` mode to try a transaction program using the program state stored on the blockchain.

**Expected behavior**
A serialized CX program needs to be "splittable".

**Desktop (please complete the following information):**
 - CX Version [e.g. 0.6.2]

### PR DESCRIPTION
**Pull request by amherag**
…saction parts.

Fixes #310

Changes:
- Added functions for splitting a serialized program. These will be used in the blockchain integration code.

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cx/serialize.go [hunk 1]
```diff
@@ -1177,3 +1177,196 @@ func Deserialize(byts []byte) (prgrm *CXProgram) {
 
 	return prgrm
 }
+
```
Comment (ingwal) [inline cx/serialize.go]: I think the code is much easier to read in general if you put the helper functions nearer the end and the main (not main() :) ) functions nearer the top.
