### PR TITLE
Fix #292: Compilation error when left hand side of an assignment expr…

### LINKED ISSUE #292: Compilation error when left hand side of an assignment expression is a struct field
**To Reproduce**
```
package main
type too struct {
	sf []f32
}
func foo()(sf []f32) {
}
func main()() {
	var t too
	t.sf = foo()
}
```
**Expected behavior**
No compilation error

**Screenshots**
```
error: tests/pending_17.cx:16 invalid reference assignment t
```

**Desktop:**
 - OS: Linux
 - CX Version : 0.6.1, https://github.com/skycoin/cx/commit/d8775bfb4500fde31a074507713fc0de47b64e11

### PR DESCRIPTION
**Pull request by amherag**
…ession is a struct field.

Fixes #292

Changes:
- The problem was related to assigning **slices** to struct fields, specifically. Fixed.

Does this change need to mentioned in CHANGELOG.md?
Yes.

### CODE REVIEW

File: cxgo/actions/functions.go [hunk 1]
```diff
@@ -1021,7 +1021,7 @@ func CopyArgFields(sym *CXArgument, arg *CXArgument) {
 
 	if len(sym.Fields) > 0 {
 		sym.Type = sym.Fields[len(sym.Fields)-1].Type
-		// sym.IsSlice = sym.Fields[len(sym.Fields) - 1].IsSlice
+		sym.IsSlice = sym.Fields[len(sym.Fields) - 1].IsSlice
```
Comment (ingwal) [inline cxgo/actions/functions.go]: Hmm, why was this disabled to begin with?  Are we destroying something else now by enabling it?
